FROM postgres:16-alpine

RUN apk add --no-cache gnupg

WORKDIR /app

COPY migration ./migration
COPY scripts/restore-railway-backup.sh ./scripts/restore-railway-backup.sh

RUN chmod +x ./scripts/restore-railway-backup.sh

CMD ["./scripts/restore-railway-backup.sh"]
